/**
 * Knowledge Auto-Population Routes
 * API endpoints for automatic knowledge base population
 */

const express = require('express');
const router = express.Router();
const KnowledgeAutoPopulationService = require('../services/knowledgeAutoPopulation');
const { authenticateToken } = require('../middleware/auth');

// Auto-populate from website
router.post('/auto-populate/:companyId', authenticateToken, async (req, res) => {
    try {
        const { websiteUrl } = req.body;
        
        if (!websiteUrl) {
            return res.status(400).json({
                success: false,
                message: 'Website URL is required'
            });
        }
        
        const result = await KnowledgeAutoPopulationService.autoPopulateFromWebsite(
            req.params.companyId, 
            websiteUrl
        );
        
        res.json({
            success: true,
            message: 'Knowledge base auto-populated successfully',
            data: result
        });
    } catch (error) {
        console.error('Auto-population failed:', error);
        res.status(500).json({
            success: false,
            message: 'Failed to auto-populate knowledge base',
            error: error.message
        });
    }
});

// Bulk import knowledge
router.post('/bulk-import/:companyId', authenticateToken, async (req, res) => {
    try {
        const { source, data } = req.body;
        
        if (!source || !data) {
            return res.status(400).json({
                success: false,
                message: 'Source and data are required'
            });
        }
        
        const result = await KnowledgeAutoPopulationService.bulkImport(
            req.params.companyId,
            source,
            data
        );
        
        res.json({
            success: true,
            message: 'Knowledge imported successfully',
            data: result
        });
    } catch (error) {
        console.error('Bulk import failed:', error);
        res.status(500).json({
            success: false,
            message: 'Failed to import knowledge',
            error: error.message
        });
    }
});

// Analyze knowledge gaps
router.get('/analyze-gaps/:companyId', authenticateToken, async (req, res) => {
    try {
        // This would analyze recent failed queries to identify knowledge gaps
        const gaps = {
            missingTopics: [
                { topic: 'Emergency Services', frequency: 12, lastAsked: '2025-07-12' },
                { topic: 'Pricing Information', frequency: 8, lastAsked: '2025-07-11' },
                { topic: 'Service Areas', frequency: 6, lastAsked: '2025-07-10' }
            ],
            suggestedQAs: [
                {
                    question: "Do you provide emergency services?",
                    suggestedAnswer: "Please contact us to discuss emergency service availability.",
                    confidence: 0.8
                },
                {
                    question: "What are your service rates?",
                    suggestedAnswer: "Our rates vary by service type. Please call for a free estimate.",
                    confidence: 0.7
                }
            ],
            improvementAreas: [
                {
                    area: "Response Coverage",
                    currentCoverage: 85,
                    targetCoverage: 95,
                    suggestions: ["Add 3-5 more Q&As about emergency services", "Include pricing guidance"]
                }
            ]
        };
        
        res.json({
            success: true,
            analysis: gaps
        });
    } catch (error) {
        console.error('Gap analysis failed:', error);
        res.status(500).json({
            success: false,
            message: 'Failed to analyze knowledge gaps',
            error: error.message
        });
    }
});

// Get knowledge suggestions
router.get('/suggestions/:companyId', authenticateToken, async (req, res) => {
    try {
        const suggestions = {
            autoGenerated: [
                {
                    type: 'seasonal',
                    question: "Do you offer holiday hours?",
                    answer: "Please contact us for holiday scheduling information.",
                    reason: "Seasonal question based on calendar"
                },
                {
                    type: 'trending',
                    question: "What safety measures do you follow?",
                    answer: "We follow all recommended safety protocols and guidelines.",
                    reason: "Trending topic in similar businesses"
                }
            ],
            industrySpecific: [
                {
                    question: "Are you licensed and insured?",
                    answer: "Yes, we are fully licensed and insured for your protection.",
                    applicableCategories: ["home-services", "contractors"]
                }
            ],
            performanceBased: [
                {
                    question: "How long does a typical service call take?",
                    answer: "Most service calls take 1-2 hours, depending on the complexity.",
                    reason: "Frequently asked but no existing answer"
                }
            ]
        };
        
        res.json({
            success: true,
            suggestions: suggestions
        });
    } catch (error) {
        console.error('Failed to get suggestions:', error);
        res.status(500).json({
            success: false,
            message: 'Failed to retrieve suggestions',
            error: error.message
        });
    }
});

module.exports = router;
